"""initial schema

Revision ID: b21d8a64fbb7
Revises: 
Create Date: 2026-08-10 14:08:12.280177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21d8a64fbb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_table('decision_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_statuses_id'), 'decision_statuses', ['id'], unique=False)
    op.create_table('survey_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_rounds_id'), 'survey_rounds', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('min_credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_table('course_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'course_name', name='uq_recommendation_dept_course')
    )
    op.create_index(op.f('ix_course_recommendations_id'), 'course_recommendations', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(length=30), nullable=True),
    sa.Column('course_department', sa.String(length=20), nullable=True),
    sa.Column('course_year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_retake_only', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_department'], ['departments.name'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_table('curriculums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('course_year', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(length=30), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'course_code', name='uq_curriculum_dept_course')
    )
    op.create_index(op.f('ix_curriculums_id'), 'curriculums', ['id'], unique=False)
    op.create_table('department_entry_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('requirement_group', sa.Integer(), nullable=False),
    sa.Column('target_grade_level', sa.Enum('A', 'B', 'C', name='gradelevelenum'), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('is_alert_required', sa.Boolean(), nullable=True),
    sa.Column('logic_operator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'admission_year', 'requirement_group', name='uq_dept_year_group')
    )
    op.create_index(op.f('ix_department_entry_requirements_id'), 'department_entry_requirements', ['id'], unique=False)
    op.create_table('requirement_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['department_entry_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_courses_id'), 'requirement_courses', ['id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('pride', sa.String(length=10), nullable=True),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('major_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('survey_round_id', sa.Integer(), nullable=False),
    sa.Column('first_choice_id', sa.Integer(), nullable=False),
    sa.Column('second_choice_id', sa.Integer(), nullable=False),
    sa.Column('decision_status_id', sa.Integer(), nullable=True),
    sa.Column('decision_scale', sa.Integer(), nullable=True),
    sa.Column('survey_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_status_id'], ['decision_statuses.id'], ),
    sa.ForeignKeyConstraint(['first_choice_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['second_choice_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_round_id'], ['survey_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_surveys_id'), 'major_surveys', ['id'], unique=False)
    op.create_table('student_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('numeric_grade', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('completion_type', sa.String(length=20), nullable=False),
    sa.Column('is_retake', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_courses_id'), 'student_courses', ['id'], unique=False)
    op.create_table('student_requirement_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('curriculum_completion_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('related_courses_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'department_id', name='uq_student_dept_eval')
    )
    op.create_index(op.f('ix_student_requirement_status_id'), 'student_requirement_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_requirement_status_id'), table_name='student_requirement_status')
    op.drop_table('student_requirement_status')
    op.drop_index(op.f('ix_student_courses_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_major_surveys_id'), table_name='major_surveys')
    op.drop_table('major_surveys')
    op.drop_table('students')
    op.drop_index(op.f('ix_requirement_courses_id'), table_name='requirement_courses')
    op.drop_table('requirement_courses')
    op.drop_index(op.f('ix_department_entry_requirements_id'), table_name='department_entry_requirements')
    op.drop_table('department_entry_requirements')
    op.drop_index(op.f('ix_curriculums_id'), table_name='curriculums')
    op.drop_table('curriculums')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_course_recommendations_id'), table_name='course_recommendations')
    op.drop_table('course_recommendations')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_survey_rounds_id'), table_name='survey_rounds')
    op.drop_table('survey_rounds')
    op.drop_index(op.f('ix_decision_statuses_id'), table_name='decision_statuses')
    op.drop_table('decision_statuses')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
